- hosts: "testserver"
  vars:
    key_file: "/etc/nginx/ssl/nginx.key"
    cert_file: "/etc/nginx/ssl/nginx.crt"
    conf_file: "/etc/nginx/sites-available/default"
    servername: "192.168.88.39"
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: create dir
      ansible.builtin.file:
        path: /etc/nginx/ssl
        state: directory
        mode: "0755"
    - name: copy tls key
      ansible.builtin.copy:
        src: files/nginx.key
        dest: "{{ key_file }}"
        owner: root 
        mоdе: "0600"
      notify: restart nginx
    - name: copy tls cert
      ansible.builtin.copy: 
        src: files/nginx.crt
        dest: "{{ cert_file }}"
      notify: restart nginx
    - name: copy nginx config file
      ansible.builtin.copy:
        src: templates/nginx.conf.j2
        dest: "{{ conf_file }}"
    - name: enable configuration
      file:
        src: "{{ conf_file }}"
        dest: "/etc/nginx/sites-enabled/default"
        state: link
      notify: restart nginx

    - name: "copy index"
      template:
        src: "templates/index.html.j2"
        dest: "/usr/share/nginx/html/index.html"
        mode: "0644"
    - name: restart nginx
      service:
        name: nginx
        state: restarted
