---
- hosts: testserver
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    servername: 192.168.88.39

  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: create dir
      ansible.builtin.file:
         path: /etc/nginx/ssl
         state: directory
         mode: '0755'

    - nае: сору TLS key
      сору: src=files/nginx.key dest={{ key_file }} owner=root оdе=0600
      notify: restart nginx

    - nае: сору TLS certificate
      сору: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx config file
      copy: src=templates/nginx.conf.j2 dest={{ conf_file }}

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src={{ conf_file }}
        state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
